[package]
name = "just_nvim"
version = "2.0.2"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Abhinandh S <abhinandhsuby@proton.me>"]
description = "Neovim plugin for encrypting and decrypting text files inside neovim using age with ease."
homepage = "https://github.com/abhi-xyz/just.nvim"
documentation = "https://github.com/abhi-xyz/just.nvim"
categories = ["command-line-utilities"]
keywords = ["tool", "utility"]

[features]
default = []
mail = ["lettre"]

[dependencies]
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10", "test", "neovim-nightly"] }
#dirs = "5.0.1"
# regex = "1.11.0"
thiserror = "2.0.6"
# serde = { version = "1.0.210", features = ["derive"] }
# serde_json = "1.0.128"
age = "0.11.0"
#toml = "0.8.19"
lettre = { version = "0.11.11", optional = true }

[lib]
name = "just"
crate-type = ["cdylib"]

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false

[lints.rust]
unsafe_code = "forbid"
unused_labels = "allow"

[lints.clippy]
unwrap_used = "forbid"
enum_glob_use = "deny"
type_complexity = "deny"
redundant_closure = "deny"
str_to_string = "deny"
correctness = "deny" # default is deny
suspicious = "deny"
complexity = "deny"
perf = "deny"
